apiVersion: v1
kind: ConfigMap
metadata:
  name: gideondb
data:
  GIDEONDB_HTTP_ADDRESS: "0.0.0.0:6333"
  GIDEONDB_DATA_PATH: /var/lib/gideondb
  GIDEONDB_WAL_SYNC: always
  GIDEONDB_CHECKPOINT_EVERY: "1000"
  GIDEONDB_REPLICATION_FACTOR: "3"
  GIDEONDB_PLACEMENT_CAPACITY: "1"
  GIDEONDB_ENABLE_STATIC_ROUTING: "true"
  GIDEONDB_PEERS: >-
    https://gideondb-0.gideondb-headless.gideondb.svc.cluster.local:6333,
    https://gideondb-1.gideondb-headless.gideondb.svc.cluster.local:6333,
    https://gideondb-2.gideondb-headless.gideondb.svc.cluster.local:6333
