apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gideondb
resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - statefulset.yaml
  - disruption-budget.yaml
  - network-policy.yaml

