apiVersion: v1
kind: Service
metadata:
  name: gideondb-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: gideondb
  ports:
    - name: https
      port: 6333
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: gideondb
spec:
  selector:
    app.kubernetes.io/name: gideondb
  ports:
    - name: https
      port: 6333
      targetPort: https
